"""
This type stub file was generated by pyright.
"""

import logging
from selenium.webdriver.remote.remote_connection import RemoteConnection

LOGGER = logging.getLogger(__name__)
PORT = 0
HOST = None
_URL = ""
class ExtensionConnection(RemoteConnection):
    def __init__(self, host, firefox_profile, firefox_binary=..., timeout=...) -> None:
        ...
    
    def quit(self, sessionId=...):
        ...
    
    def connect(self):
        """Connects to the extension and retrieves the session id."""
        ...
    
    @classmethod
    def connect_and_quit(self):
        """Connects to an running browser and quit immediately."""
        ...
    
    @classmethod
    def is_connectable(self):
        """Trys to connect to the extension but do not retrieve context."""
        ...
    


class ExtensionConnectionError(Exception):
    """An internal error occurred int the extension.

    Might be caused by bad input or bugs in webdriver
    """
    ...


