"""
This type stub file was generated by pyright.
"""

class FirefoxBinary(object):
    NO_FOCUS_LIBRARY_NAME = ...
    def __init__(self, firefox_path=..., log_file=...) -> None:
        """
        Creates a new instance of Firefox binary.

        :Args:
         - firefox_path - Path to the Firefox executable. By default, it will be detected from the standard locations.
         - log_file - A file object to redirect the firefox process output to. It can be sys.stdout.
                      Please note that with parallel run the output won't be synchronous.
                      By default, it will be redirected to /dev/null.
        """
        ...
    
    def add_command_line_options(self, *args):
        ...
    
    def launch_browser(self, profile, timeout=...):
        """Launches the browser for the given profile name.
        It is assumed the profile already exists.
        """
        ...
    
    def kill(self):
        """Kill the browser.

        This is useful when the browser is stuck.
        """
        ...
    
    def which(self, fname):
        """Returns the fully qualified path by searching Path of the given
        name"""
        ...
    


