"""
This type stub file was generated by pyright.
"""

from selenium.webdriver.common import service

class Service(service.Service):
    """
    Object that manages the starting and stopping of the ChromeDriver
    """
    def __init__(self, executable_path, port=..., service_args=..., log_path=..., env=...) -> None:
        """
        Creates a new instance of the Service

        :Args:
         - executable_path : Path to the ChromeDriver
         - port : Port the service is running on
         - service_args : List of args to pass to the chromedriver service
         - log_path : Path for the chromedriver service to log to"""
        ...
    
    def command_line_args(self):
        ...
    


