"""
This type stub file was generated by pyright.
"""

import threading

CAKEY = _currentdir('ca.key')
CACERT = _currentdir('ca.crt')
CERTKEY = _currentdir('cert.key')
CERTDIR = _currentdir('certs/')
_LOCK = threading.Lock()
DEFAULT_OPENSSL_CONF = """
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = %s
"""
def generate(hostname, certdir):
    """Generate a self-signed certificate for the supplied
    hostname if one does not already exist.

    Args:
        hostname: The hostname of the remote server.
        certdir: The directory to store the generated certificates.
    """
    ...

