"""
This type stub file was generated by pyright.
"""

from http.client import HTTPMessage
from typing import Dict, Iterable, List, Tuple, Union

"""Houses the classes used to transfer request and response data between components. """
class HTTPHeaders(HTTPMessage):
    """Used to hold HTTP headers."""
    def __repr__(self):
        ...
    


class Request:
    """Represents an HTTP request."""
    def __init__(self, *, method: str, url: str, headers: Iterable[Tuple[str, str]], body: bytes = ...) -> None:
        """Initialise a new Request object.

        Args:
            method: The request method - GET, POST etc.
            url: The request URL.
            headers: The request headers as an iterable of 2-element tuples.
            body: The request body as bytes.
        """
        ...
    
    @property
    def body(self) -> bytes:
        """Get the request body.

        Returns: The request body as bytes.
        """
        ...
    
    @body.setter
    def body(self, b: bytes):
        ...
    
    @property
    def querystring(self) -> str:
        """Get the query string from the request.

        Returns: The query string.
        """
        ...
    
    @querystring.setter
    def querystring(self, qs: str):
        ...
    
    @property
    def params(self) -> Dict[str, Union[str, List[str]]]:
        """Get the request parameters.

        Parameters are returned as a dictionary. Each dictionary entry will have a single
        string value, unless a parameter happens to occur more than once in the request,
        in which case the value will be a list of strings.

        Returns: A dictionary of request parameters.
        """
        ...
    
    @params.setter
    def params(self, p: Dict[str, Union[str, List[str]]]):
        ...
    
    @property
    def path(self) -> str:
        """Get the request path.

        Returns: The request path.
        """
        ...
    
    @path.setter
    def path(self, p: str):
        ...
    
    def create_response(self, status_code: int, headers: Union[Dict[str, str], Iterable[Tuple[str, str]]] = ..., body: bytes = ...):
        """Create a response object and attach it to this request."""
        ...
    
    def abort(self, error_code: int = ...):
        """Convenience method for signalling that this request is to be terminated
        with a specific error code.
        """
        ...
    
    def __repr__(self):
        ...
    
    def __str__(self) -> str:
        ...
    


class Response:
    """Represents an HTTP response."""
    def __init__(self, *, status_code: int, reason: str, headers: Iterable[Tuple[str, str]], body: bytes = ...) -> None:
        """Initialise a new Response object.

        Args:
            status_code: The status code.
            reason: The reason message (e.g. "OK" or "Not Found").
            headers: The response headers as an iterable of 2-element tuples.
            body: The response body as bytes.
        """
        ...
    
    @property
    def body(self) -> bytes:
        """Get the response body.

        Returns: The response body as bytes.
        """
        ...
    
    @body.setter
    def body(self, b: bytes):
        ...
    
    def __repr__(self):
        ...
    
    def __str__(self) -> str:
        ...
    


