"""
This type stub file was generated by pyright.
"""

from http.server import HTTPServer
from socketserver import ThreadingMixIn

class BoundedThreadingMixin(ThreadingMixIn):
    """Mix-in class that allows for a maximum number of threads to handle requests."""
    def __init__(self, max_threads, *args, **kwargs) -> None:
        ...
    
    def process_request_thread(self, request, client_address):
        ...
    
    def process_request(self, request, client_address):
        ...
    


class ProxyHTTPServer(BoundedThreadingMixin, HTTPServer):
    address_family = ...
    daemon_threads = ...
    def __init__(self, host, port, *args, options=..., **kwargs) -> None:
        ...
    
    def address(self):
        """Get a tuple of the address and port the server is listening on."""
        ...
    
    def shutdown(self):
        ...
    
    def handle_error(self, request, client_address):
        ...
    


