"""
This type stub file was generated by pyright.
"""

from selenium.webdriver.common import service

class Service(service.Service):
    """
    Object that manages the starting and stopping of the SafariDriver
    """
    def __init__(self, executable_path, port=..., quiet=..., service_args=...) -> None:
        """
        Creates a new instance of the Service

        :Args:
         - executable_path : Path to the SafariDriver
         - port : Port the service is running on
         - quiet : Suppress driver stdout and stderr
         - service_args : List of args to pass to the safaridriver service """
        ...
    
    def command_line_args(self):
        ...
    
    @property
    def service_url(self):
        """
        Gets the url of the SafariDriver Service
        """
        ...
    


