"""
This type stub file was generated by pyright.
"""

from selenium.webdriver.common import service

class Service(service.Service):
    """
    Object that manages the starting and stopping of the IEDriver
    """
    def __init__(self, executable_path, port=..., host=..., log_level=..., log_file=...) -> None:
        """
        Creates a new instance of the Service

        :Args:
         - executable_path : Path to the IEDriver
         - port : Port the service is running on
         - host : IP address the service port is bound
         - log_level : Level of logging of service, may be "FATAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE".
           Default is "FATAL".
         - log_file : Target of logging of service, may be "stdout", "stderr" or file path.
           Default is "stdout"."""
        ...
    
    def command_line_args(self):
        ...
    


