"""
This type stub file was generated by pyright.
"""

class FakeUserAgent(object):
    def __init__(self, cache=..., use_cache_server=..., path=..., fallback=..., verify_ssl=..., safe_attrs=...) -> None:
        ...
    
    def load(self):
        ...
    
    def update(self, cache=...):
        ...
    
    def __getitem__(self, attr):
        ...
    
    def __getattr__(self, attr):
        ...
    
    @property
    def random(self) -> str:
        ...
    


UserAgent = FakeUserAgent
