"""
This type stub file was generated by pyright.
"""

urlopen_has_ssl_context = 'context' in urlopen_args
def get(url, verify_ssl=...):
    ...

def get_browsers(verify_ssl=...):
    """
    very very hardcoded/dirty re/split stuff, but no dependencies
    """
    ...

def get_browser_versions(browser, verify_ssl=...):
    """
    very very hardcoded/dirty re/split stuff, but no dependencies
    """
    ...

def load(use_cache_server=..., verify_ssl=...):
    ...

def write(path, data):
    ...

def read(path):
    ...

def exist(path):
    ...

def rm(path):
    ...

def update(path, use_cache_server=..., verify_ssl=...):
    ...

def load_cached(path, use_cache_server=..., verify_ssl=...):
    ...

