"""
This type stub file was generated by pyright.
"""

class InputDevice(object):
    """
        Describes the input device being used for the action.
    """
    def __init__(self, name=...) -> None:
        ...
    
    def add_action(self, action):
        """

        """
        ...
    
    def clear_actions(self):
        ...
    
    def create_pause(self, duraton=...):
        ...
    


