"""
This type stub file was generated by pyright.
"""

from .interaction import Interaction

class KeyActions(Interaction):
    def __init__(self, source=...) -> None:
        ...
    
    def key_down(self, letter):
        ...
    
    def key_up(self, letter):
        ...
    
    def pause(self, duration=...):
        ...
    
    def send_keys(self, text):
        ...
    


