"""
This type stub file was generated by pyright.
"""

class Service(object):
    def __init__(self, executable, port=..., log_file=..., env=..., start_error_message=...) -> None:
        ...
    
    @property
    def service_url(self):
        """
        Gets the url of the Service
        """
        ...
    
    def command_line_args(self):
        ...
    
    def start(self):
        """
        Starts the Service.

        :Exceptions:
         - WebDriverException : Raised either when it can't start the service
           or when it can't connect to the service
        """
        ...
    
    def assert_process_still_running(self):
        ...
    
    def is_connectable(self):
        ...
    
    def send_remote_shutdown_command(self):
        ...
    
    def stop(self):
        """
        Stops the service.
        """
        ...
    
    def __del__(self):
        ...
    


